import collections
import uuid
try:
    from urllib import parse
except:
    from urlparse import urlparse as parse

from emailage import protocols
from emailage import signature
from emailage.client import EmailageClient
import time
import sys
import io

Query = collections.namedtuple('Query', 'customer_email customer_ip')


def create_emailage_client():
    # Replace with the credentials provided to you
    user_credentials = {
     'secret': 'E4D2778DD32D41248347E2EEC4448685',
     'token': 'EA5E3B2D8F5646FB81093FF0D116C88E'
    }

    # Target the Sandbox environment during testing
    client = EmailageClient(user_credentials['secret'], user_credentials['token'], sandbox=True)
    client.domain = 'https://devapi042016.eaorg.us'
    client.session.mount(client.domain, EmailageClient.Adapter())

    return client


def example_query():

    client = create_emailage_client()

    your_query = Query(customer_email='britney.spears@aol.com', customer_ip='192.168.1.1')

    # A unique identifier generated by you to track the request or customer
    customer_unique_id = uuid.uuid4()

    fraud_report = client.query(your_query, urid=customer_unique_id)
    sys.stdout(fraud_report['results'])


def main():
    example_query()


if __name__ == '__main__':
    main()
