site_name: emailage
site_description: Emailage API client written in Python
site_author: Emailage Dev Team
repo_url: https://github.com/emailage/Emailage_Python
# google_analytics: ['XX-XXXXXXXX-XX', 'auto']

theme: mkdocs

nav:
- Home: README.md

- About:
  - 'Release Notes': about/changes.md
  - Contributing: about/contributing.md
  - License: about/license.md
